name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Install dependencies
      run: uv sync

    - name: Lint with ruff
      run: uv run ruff check .

    - name: Format check with ruff
      run: uv run ruff format --check .

    - name: Type check with mypy
      run: uv run mypy .

    - name: Test with pytest (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      env:
        DISPLAY: ':99'
      run: xvfb-run -a uv run pytest --cov=icon_converter --cov-report=xml --cov-report=term-missing

    - name: Test with pytest (Windows/macOS)
      if: matrix.os != 'ubuntu-latest'
      run: uv run pytest --cov=icon_converter --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
